import { computed, type ComputedRef } from 'vue'
import { useAppConfig } from '#imports'
import { defu } from 'defu'
import type { Collections } from '@nuxt/content'
import type { AppConfig } from 'nuxt/schema'
import collectionsMeta from '#content-traits-meta'

declare module '#content-traits-meta' {
  const meta: Record<string, { active: string[] }>
  export default meta
}

/**
 * Type helper to extract and merge trait configurations from AppConfig.
 */
export type InferTraitConfig<K extends keyof Collections>
  = (AppConfig extends { content: { traits?: infer T } } ? T : Record<string, unknown>)
    & (AppConfig extends { content: { collections?: { [P in K]?: infer C } } } ? C : Record<string, unknown>)

/**
 * Provides reactive trait configuration for a Nuxt Content collection.
 * Trait metadata is read from a build-time virtual module (#content-traits-meta)
 * generated by defineContentConfig, then deep-merged with global and
 * collection-level overrides from `app.config.ts`.
 * @template K - The collection name key
 * @param collectionName - The name of the collection
 */
export function useCollectionTraits<K extends keyof Collections>(collectionName: K): {
  activeTraits: ComputedRef<string[]>
  traitConfig: ComputedRef<InferTraitConfig<K>>
  hasTrait: (name: string) => boolean
} {
  const appConfig = useAppConfig() as AppConfig & { content?: { traits?: Record<string, unknown>, collections?: Record<string, Record<string, unknown>> } }

  const meta = (collectionsMeta as Record<string, { active: string[] }>)[String(collectionName)]

  const activeTraits = computed<string[]>(() => meta?.active ?? [])

  const traitConfig = computed<InferTraitConfig<K>>(() => {
    const globalOverrides = appConfig.content?.traits ?? {}
    const collectionOverrides = appConfig.content?.collections?.[String(collectionName)] ?? {}
    return defu(collectionOverrides, globalOverrides) as InferTraitConfig<K>
  })

  const hasTrait = (name: string): boolean => activeTraits.value.includes(name)

  return { activeTraits, traitConfig, hasTrait }
}
