import { computed } from 'vue'
import { useAsyncData } from '#imports'

interface TraitDocument {
  _traits?: {
    active?: string[]
    config?: Record<string, unknown>
  }
}

/**
 * Extracts the trait configuration and active features for a given Nuxt Content collection.
 * @param collectionName The name of the collection (e.g., 'article', 'event')
 * @template T - The type of the merged trait configuration
 */
export function useCollectionTraits<T = Record<string, unknown>>(collectionName: string) {
  // In Nuxt Content v3, we can fetch the collection traits via the injected _traits property.
  // We fetch the first document to get the trait configuration.
  const { data: document } = useAsyncData(`collection-meta-${collectionName}`, async () => {
    // @ts-expect-error - queryCollection is auto-generated by Nuxt Content
    return await queryCollection(collectionName).first()
  })

  const activeTraits = computed<string[]>(() => (document.value as TraitDocument)?._traits?.active ?? [])
  const traitConfig = computed<T>(() => (document.value as TraitDocument)?._traits?.config as T ?? {} as T)

  const hasTrait = (traitName: string) => activeTraits.value.includes(traitName)

  return {
    activeTraits,
    traitConfig,
    hasTrait,
  }
}
