import { computed } from 'vue'
import { useAsyncData } from '#imports'

/**
 * Extracts the trait configuration and active features for a given Nuxt Content collection.
 * @param collectionName The name of the collection (e.g., 'article', 'event')
 */
export function useCollectionTraits(collectionName: string) {
  // In Nuxt Content v3, we can fetch collection meta via the auto-generated queryCollection api.
  // We use a lightweight async data call to get the collection meta.
  const { data: collectionMeta } = useAsyncData(`collection-meta-${collectionName}`, async () => {
    // @ts-expect-error - queryCollection is auto-generated by Nuxt Content
    const collection = await queryCollection(collectionName).first()
    return collection?.meta
  })

  const activeTraits = computed<string[]>(() => collectionMeta.value?.traits?.active ?? [])
  const traitConfig = computed<Record<string, unknown>>(() => collectionMeta.value?.traits?.config ?? {})

  const hasTrait = (traitName: string) => activeTraits.value.includes(traitName)

  return {
    activeTraits,
    traitConfig,
    hasTrait,
  }
}
